use [TasteWhisky_PROD];
GO
USE [master]
GO
ALTER DATABASE [TasteWhisky_PROD] SET  SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
USE [master]
GO
DROP DATABASE [TasteWhisky_PROD]
GO
CREATE DATABASE TasteWhisky_PROD;